"""Model and processing configuration; contains no region-specific paths."""
from pathlib import Path
import torch

ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "results"
MODEL_DIR = OUTPUT_DIR / "models"
TIFF_BAND_ORDER = ["B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B11", "B12"]
MODEL_BAND_NAMES = ["B2", "B3", "B4", "B5", "B7", "B8", "B11", "B12"]
REQUIRED_NONCONSTANT_BANDS = MODEL_BAND_NAMES.copy()
TILE_SIZE, TRAIN_STRIDE, TEST_STRIDE = 256, 128, 128
BATCH_SIZE, NUM_WORKERS, FINAL_TRAINING_EPOCHS = 4, 0, 25
LEARNING_RATE, WEIGHT_DECAY = 1e-4, 1e-5
MIN_THRESHOLD, MAX_THRESHOLD, THRESHOLD_GRID_SIZE = .05, .80, 31
MIN_VALID_FRACTION, MIN_POSITIVE_PIXELS = .50, 32
NEGATIVE_TO_POSITIVE_RATIO, MAX_POSITIVE_WEIGHT = 4., 1.
TVERSKY_ALPHA, TVERSKY_BETA, TVERSKY_WEIGHT = .8, .2, .25
MIN_VALIDATION_PRECISION, MIN_PER_CITY_VALIDATION_PRECISION, MIN_VALIDATION_RECALL = .60, .25, .05
NEGATIVE_PIXEL_WEIGHT, FBETA_BETA = 1.25, .25
MIN_COMPONENT_PIXELS_CANDIDATES = [0, 16, 49, 81]
MAX_POSITIVE_FRACTION_CANDIDATES = [.01, .02, .03, .05, .08, 1.]
TOP_OPERATING_CANDIDATES = 12
TEXTURE_WINDOW, GLCM_LEVELS, GLCM_DISTANCE, GLCM_DIRECTION = 7, 32, 1, (0, 1)
RANDOM_SEED, CONSTANT_BAND_POLICY, USE_AMP = 42, "warn", True
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

